### ISSUE TITLE
How to "source .env" in Elixir to "load" Environment Variables from .env file?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-environment-variables#18]
Scenario:
we have an `.env` file that contains several environment variables.
We want to run the equivalent of
```sh
source .env
```
but from within our `config.exs` file, so that it's run each time the app is started
(_such that the `source .env` command does not need to be run **manually**_)

We tried the following three variants:
```elixir
System.cmd("source", [".env"])
:os.cmd("source .env")
"source .env" |> String.to_charlist |> :os.cmd
```
Sadly _none_ of them worked for setting the environment variables.

Ended up cobbling together the following code:
```elixir
try do
  File.stream!("./.env")
    |> Stream.map(&String.trim_trailing/1) # remove excess whitespace
    |> Enum.each(fn line -> line           # loop through each line
      |> String.replace("export ", "")     # remove "export" from line
      |> String.split("=")                 # split on the "=" (equals sign)
      |> Enum.reduce(fn(value, key) ->     # stackoverflow.com/q/33055834/1148249
        System.put_env(key, value)         # set each environment variable
      end)
    end)
rescue
  _ -> IO.puts "no .env file found!"
end
```
Which _does_ work.
But it _so many_ lines of code ...

Does anyone know _why_ the `source .env` does not work?

**Comment by nelsonic** [comment]
Considering just "porting" over `env2` to elixir ... https://github.com/dwyl/env2/blob/master/lib/env.js
🤔

**Comment by curioustushar** [comment]
@nelsonic  check few already available options https://github.com/avdi/dotenv_elixir  https://github.com/BlakeWilliams/envy .

**Comment by nelsonic** [comment]
@cse-tushar _thanks_. 
had a look at the options ... 
I think the _best_ course of action might be to use the "Elixir Way" ... 🤔 
![image](https://user-images.githubusercontent.com/194400/38560382-69fad7a2-3ccd-11e8-88a4-21c23ae7008e.png)
That way I'm not encouraging _others_ to "bend" Elixir/Phoenix to do something it's not meant to do ...

**Comment by hipertracker** [comment]
OptionParse can handle ini files including .env. You only need add the section to the file.  Like in this example where I am using  .env file to set the database in Phoenix. https://gist.github.com/hipertracker/5338d75e220b200dc92f6be3af65f5b5

**Comment by nelsonic** [comment]
@hipertracker that's a good gist for the DIY approach. 👍 
Going to try [`envy`](https://github.com/BlakeWilliams/envy) on our current project to simplify development. Thanks @curioustushar 👍

**Comment by msudgh** [comment]
`envy` not worked for me. How `.env` can be consumed in `config` dir by replacement envs?

**Comment by nelsonic** [comment]
https://github.com/dwyl/envar
